/**
 * Kysely row types for database views and materialized views.
 * Auto-generated by scripts/dev/generate-kysely-view-types.ts
 * Do not edit by hand.
 */

export interface AdminCommunityActivitySummaryRow {
  HostCollectiveId?: number;
  CollectiveId?: number;
  FromCollectiveId?: number;
  activities?: Record<string, unknown> | unknown[];
  relations?: Record<string, unknown> | unknown[];
  lastInteractionAt?: string;
  firstInteractionAt?: string;
}

export interface AdminCommunityHostTransactionSummaryRow {
  FromCollectiveId?: number;
  HostCollectiveId?: number;
  hostCurrency?: string;
  kind?: string;
  debitTotal?: number;
  debitCount?: number;
  creditTotal?: number;
  creditCount?: number;
  refundDebitTotal?: number;
  refundDebitCount?: number;
}

export interface AdminCommunityHostYearlyTransactionSummaryRow {
  FromCollectiveId?: number;
  HostCollectiveId?: number;
  hostCurrency?: string;
  year?: number;
  kind?: string;
  debitTotal?: number;
  debitCount?: number;
  creditTotal?: number;
  creditCount?: number;
  refundDebitTotal?: number;
  refundDebitCount?: number;
}

export interface AdminCommunityTransactionSummaryRow {
  FromCollectiveId?: number;
  CollectiveId?: number;
  HostCollectiveId?: number;
  year?: number;
  kind?: string;
  hostCurrency?: string;
  debitTotal?: number;
  debitCount?: number;
  creditTotal?: number;
  creditCount?: number;
  refundDebitTotal?: number;
  refundDebitCount?: number;
  debitTotalAcc?: number;
  debitCountAcc?: number;
  creditTotalAcc?: number;
  creditCountAcc?: number;
  refundDebitTotalAcc?: number;
  refundDebitCountAcc?: number;
}

export interface CollectiveBalanceCheckpointRow {
  id?: number;
  CollectiveId?: number;
  balance?: number;
  hostCurrency?: string;
  createdAt?: string;
  budgetVersion?: string;
  HostCollectiveId?: number;
}

export interface CollectiveOrderStatsRow {
  CollectiveId?: number;
  errorRate1M?: number;
  errorRate3M?: number;
  errorRate12M?: number;
  successRate1M?: number;
  successRate3M?: number;
  successRate12M?: number;
  numOrders1M?: number;
  numOrders3M?: number;
  numOrders12M?: number;
}

export interface CollectiveTagStatsRow {
  tag?: string;
  count?: number;
  HostCollectiveId?: number;
}

export interface CollectiveTransactionStatsRow {
  id?: number;
  LatestTransactionCreatedAt?: string;
  count?: number;
  totalAmountReceivedInHostCurrency?: number;
  totalNetAmountReceivedInHostCurrency?: number;
  totalAmountSpentInHostCurrency?: number;
  totalNetAmountSpentInHostCurrency?: number;
  hostCurrency?: string;
}

export interface CurrentCollectiveBalanceRow {
  CollectiveId?: number;
  netAmountInHostCurrency?: number;
  disputedNetAmountInHostCurrency?: number;
  hostCurrency?: string;
}

export interface CurrentCollectiveTransactionStatsRow {
  CollectiveId?: number;
  totalAmountReceivedInHostCurrency?: number;
  totalNetAmountReceivedInHostCurrency?: number;
  totalAmountSpentInHostCurrency?: number;
  totalNetAmountSpentInHostCurrency?: number;
  hostCurrency?: string;
}

export interface ExpenseTagStatsRow {
  tag?: string;
  count?: number;
  HostCollectiveId?: number;
  CollectiveId?: number;
}

export interface HostMonthlyTransactionsRow {
  date?: string;
  HostCollectiveId?: number;
  amountInHostCurrency?: number;
  platformFeeInHostCurrency?: number;
  hostFeeInHostCurrency?: number;
  paymentProcessorFeeInHostCurrency?: number;
  taxAmountInHostCurrency?: number;
  netAmountInHostCurrency?: number;
  kind?: string;
  isRefund?: boolean;
  hostCurrency?: string;
  type?: string;
  isHost?: boolean;
  expenseType?: string;
  refreshedAt?: string;
}

export interface TransactionBalancesRow {
  id?: number;
  CollectiveId?: number;
  createdAt?: string;
  hostCurrency?: string;
  rank?: number;
  balance?: number;
}

/**
 * Database interface containing only views and materialized views.
 * Use with Kysely when querying views, e.g. getKysely().selectFrom('ViewName').selectAll()
 */
export type ViewsDatabase = {
  AdminCommunityActivitySummary: AdminCommunityActivitySummaryRow;
  AdminCommunityHostTransactionSummary: AdminCommunityHostTransactionSummaryRow;
  AdminCommunityHostYearlyTransactionSummary: AdminCommunityHostYearlyTransactionSummaryRow;
  AdminCommunityTransactionSummary: AdminCommunityTransactionSummaryRow;
  CollectiveBalanceCheckpoint: CollectiveBalanceCheckpointRow;
  CollectiveOrderStats: CollectiveOrderStatsRow;
  CollectiveTagStats: CollectiveTagStatsRow;
  CollectiveTransactionStats: CollectiveTransactionStatsRow;
  CurrentCollectiveBalance: CurrentCollectiveBalanceRow;
  CurrentCollectiveTransactionStats: CurrentCollectiveTransactionStatsRow;
  ExpenseTagStats: ExpenseTagStatsRow;
  HostMonthlyTransactions: HostMonthlyTransactionsRow;
  TransactionBalances: TransactionBalancesRow;
};
