/**
 * Kysely row types for database views and materialized views.
 * Auto-generated by scripts/dev/generate-kysely-view-types.ts
 * Do not edit by hand.
 */

export interface CollectiveBalanceCheckpointRow {
  id?: number;
  CollectiveId?: number;
  balance?: number;
  hostCurrency?: string;
  createdAt?: string;
  budgetVersion?: string;
  HostCollectiveId?: number;
}

export interface CollectiveOrderStatsRow {
  CollectiveId?: number;
  errorRate1M?: number;
  errorRate3M?: number;
  errorRate12M?: number;
  successRate1M?: number;
  successRate3M?: number;
  successRate12M?: number;
  numOrders1M?: number;
  numOrders3M?: number;
  numOrders12M?: number;
}

export interface CollectiveTagStatsRow {
  tag?: string;
  count?: number;
  HostCollectiveId?: number;
}

export interface CollectiveTransactionStatsRow {
  id?: number;
  LatestTransactionCreatedAt?: string;
  count?: number;
  totalAmountReceivedInHostCurrency?: number;
  totalNetAmountReceivedInHostCurrency?: number;
  totalAmountSpentInHostCurrency?: number;
  totalNetAmountSpentInHostCurrency?: number;
  hostCurrency?: string;
}

export interface CommunityActivitySummaryRow {
  HostCollectiveId?: number;
  CollectiveId?: number;
  FromCollectiveId?: number;
  activities?: Record<string, unknown> | unknown[];
  relations?: Record<string, unknown> | unknown[];
  lastInteractionAt?: string;
  firstInteractionAt?: string;
}

export interface CommunityHostTransactionsAggregatedRow {
  FromCollectiveId?: number;
  HostCollectiveId?: number;
  hostCurrency?: string;
  years?: number[];
  expenseTotal?: number[];
  expenseCount?: number[];
  contributionTotal?: number[];
  contributionCount?: number[];
  expenseTotalAcc?: number[];
  expenseCountAcc?: number[];
  contributionTotalAcc?: number[];
  contributionCountAcc?: number[];
}

export interface CommunityHostTransactionSummaryRow {
  FromCollectiveId?: number;
  HostCollectiveId?: number;
  year?: number;
  hostCurrency?: string;
  expenseTotal?: number;
  expenseCount?: number;
  contributionTotal?: number;
  contributionCount?: number;
  orderCount?: number;
  expenseTotalAcc?: number;
  expenseCountAcc?: number;
  contributionTotalAcc?: number;
  contributionCountAcc?: number;
  orderCountAcc?: number;
}

export interface CurrentCollectiveBalanceRow {
  CollectiveId?: number;
  netAmountInHostCurrency?: number;
  disputedNetAmountInHostCurrency?: number;
  hostCurrency?: string;
}

export interface CurrentCollectiveTransactionStatsRow {
  CollectiveId?: number;
  totalAmountReceivedInHostCurrency?: number;
  totalNetAmountReceivedInHostCurrency?: number;
  totalAmountSpentInHostCurrency?: number;
  totalNetAmountSpentInHostCurrency?: number;
  hostCurrency?: string;
}

export interface ExpenseTagStatsRow {
  tag?: string;
  count?: number;
  HostCollectiveId?: number;
  CollectiveId?: number;
}

export interface HostMonthlyContributionsRow {
  date?: string;
  HostCollectiveId?: number;
  amountInHostCurrency?: number;
  count?: number;
  hostCurrency?: string;
  isHost?: boolean;
  refreshedAt?: string;
}

export interface HostMonthlyTransactionsRow {
  date?: string;
  HostCollectiveId?: number;
  amountInHostCurrency?: number;
  platformFeeInHostCurrency?: number;
  hostFeeInHostCurrency?: number;
  paymentProcessorFeeInHostCurrency?: number;
  taxAmountInHostCurrency?: number;
  netAmountInHostCurrency?: number;
  kind?: string;
  isRefund?: boolean;
  hostCurrency?: string;
  type?: string;
  isHost?: boolean;
  expenseType?: string;
  refreshedAt?: string;
}

export interface TransactionBalancesRow {
  id?: number;
  CollectiveId?: number;
  createdAt?: string;
  hostCurrency?: string;
  rank?: number;
  balance?: number;
}

/**
 * Database interface containing only views and materialized views.
 * Use with Kysely when querying views, e.g. getKysely().selectFrom('ViewName').selectAll()
 */
export type ViewsDatabase = {
  CollectiveBalanceCheckpoint: CollectiveBalanceCheckpointRow;
  CollectiveOrderStats: CollectiveOrderStatsRow;
  CollectiveTagStats: CollectiveTagStatsRow;
  CollectiveTransactionStats: CollectiveTransactionStatsRow;
  CommunityActivitySummary: CommunityActivitySummaryRow;
  CommunityHostTransactionsAggregated: CommunityHostTransactionsAggregatedRow;
  CommunityHostTransactionSummary: CommunityHostTransactionSummaryRow;
  CurrentCollectiveBalance: CurrentCollectiveBalanceRow;
  CurrentCollectiveTransactionStats: CurrentCollectiveTransactionStatsRow;
  ExpenseTagStats: ExpenseTagStatsRow;
  HostMonthlyContributions: HostMonthlyContributionsRow;
  HostMonthlyTransactions: HostMonthlyTransactionsRow;
  TransactionBalances: TransactionBalancesRow;
};
