import config from 'config';
import { omit, truncate } from 'lodash';
import { CountryCode, ItemPublicTokenExchangeResponse, LinkTokenCreateRequest, Products } from 'plaid';

import { Service } from '../../constants/connected-account';
import PlatformConstants from '../../constants/platform';
import { Collective, ConnectedAccount, sequelize, TransactionsImport, User } from '../../models';
import { sessionCache } from '../cache';
import { reportErrorToSentry } from '../sentry';

import { getPlaidClient } from './client';
import { getPlaidWebhookUrl } from './webhooks';

// See https://plaid.com/docs/api/link/#link-token-create-request-language
const PlaidSupportedLocales = [
  'da',
  'nl',
  'en',
  'et',
  'fr',
  'de',
  'hi',
  'it',
  'lv',
  'lt',
  'no',
  'pl',
  'pt',
  'ro',
  'es',
  'sv',
  'vi',
] as const;

const getPlaidLanguage = (locale: string): (typeof PlaidSupportedLocales)[number] => {
  if (locale) {
    locale = locale.toLowerCase().split('-')[0].trim();
    if ((PlaidSupportedLocales as readonly string[]).includes(locale)) {
      return locale as (typeof PlaidSupportedLocales)[number];
    }
  }

  return 'en';
};

/**
 * Plaid `link_token`s are generated by an authenticated host admin, but the `public_token` that comes
 * back once the user completes the Plaid Link flow only proves that _some_ Item was created; it says
 * nothing about which host it was generated for. Without binding it to its initiator, anyone who gets
 * hold of a `public_token` (e.g. a host admin intercepting it from a shared browser, proxy, or logs)
 * could exchange it themselves and bind somebody else's authorized bank connection to their own host.
 *
 * We record the initiator when the link token is created, and verify it when the connection is
 * completed, keyed by the `link_token` itself (which the frontend already threads through both the
 * regular and OAuth-redirect Plaid Link flows).
 */
type PlaidLinkSession = { CollectiveId: number; UserId: number };

/** Fallback TTL used if we can't compute one from Plaid's own `expiration` field. */
const PLAID_LINK_SESSION_TTL = 60 * 30;

export const getPlaidLinkSessionCacheKey = (linkToken: string): string => `plaid:link-session:${linkToken}`;

const recordPlaidLinkSession = async (
  linkToken: string,
  session: PlaidLinkSession,
  expiration?: string,
): Promise<void> => {
  let ttl = PLAID_LINK_SESSION_TTL;
  if (expiration) {
    const expiresInSeconds = Math.floor((new Date(expiration).getTime() - Date.now()) / 1000);
    if (expiresInSeconds > 0) {
      ttl = expiresInSeconds;
    }
  }

  await sessionCache.set(getPlaidLinkSessionCacheKey(linkToken), session, ttl);
};

/**
 * Makes sure `linkToken` was generated by `remoteUser` for the account identified by `CollectiveId`.
 *
 * This deliberately **fails closed**: a missing session (expired, evicted from the cache, or created
 * before this check was deployed) is rejected. Accepting unbound link tokens would defeat the control
 * entirely, since an attacker only has to wait for the entry to expire before claiming a public token
 * they did not generate. Users hitting this simply need to restart the connection flow.
 */
const assertPlaidLinkTokenWasInitiatedBy = async (
  remoteUser: User,
  CollectiveId: number,
  linkToken: string,
): Promise<void> => {
  const session: PlaidLinkSession | undefined = await sessionCache.get(getPlaidLinkSessionCacheKey(linkToken));

  if (!session || session.CollectiveId !== CollectiveId || session.UserId !== remoteUser.id) {
    throw new Error(
      'This bank connection request could not be verified. Please restart the connection process from your dashboard.',
    );
  }
};

const clearPlaidLinkSession = async (linkToken: string): Promise<void> => {
  await sessionCache.delete(getPlaidLinkSessionCacheKey(linkToken));
};

export const generatePlaidLinkToken = async (
  remoteUser: User,
  host: Collective,
  params: {
    products: readonly (Products | `${Products}`)[];
    countries: readonly (CountryCode | `${CountryCode}`)[];
    locale: string;
    accessToken?: string;
    /** If `accessToken` is provided, this flag will enable the account selection flow */
    accountSelectionEnabled?: boolean;
  },
) => {
  /* eslint-disable camelcase */
  const linkTokenConfig: LinkTokenCreateRequest = {
    user: { client_user_id: remoteUser.id.toString() },
    client_name: PlatformConstants.PlatformName,
    language: getPlaidLanguage(params.locale),
    products: params.products as Products[],
    country_codes: params.countries as CountryCode[],
    webhook: getPlaidWebhookUrl(),
    redirect_uri: `${config.host.website}/services/plaid/oauth/callback`, // Redirect URL must be listed in https://dashboard.plaid.com/developers/api
  };

  if (params.accessToken) {
    linkTokenConfig.access_token = params.accessToken;
    if (params.accountSelectionEnabled) {
      linkTokenConfig.update = { account_selection_enabled: true };
    }
  }
  /* eslint-enable camelcase */

  try {
    const PlaidClient = getPlaidClient();
    const tokenResponse = await PlaidClient.linkTokenCreate(linkTokenConfig);

    // Bind the link token to whoever initiated it, so that nobody else can claim the resulting
    // public token for a different host. See `assertPlaidLinkTokenWasInitiatedBy`.
    await recordPlaidLinkSession(
      tokenResponse.data['link_token'],
      { CollectiveId: host.id, UserId: remoteUser.id },
      tokenResponse.data['expiration'],
    );

    return tokenResponse.data;
  } catch (e) {
    reportErrorToSentry(e, { extra: { linkTokenConfig }, user: remoteUser });
    throw new Error('Failed to generate Plaid link token');
  }
};

export const connectPlaidAccount = async (
  remoteUser: User,
  host: Collective,
  publicToken: string,
  linkToken: string,
  { sourceName, name }: { sourceName?: string; name?: string },
) => {
  // Permissions check
  if (!remoteUser.isAdminOfCollective(host)) {
    throw new Error('You must be an admin of the host to connect a Plaid account to it');
  } else if (!host.hasMoneyManagement) {
    throw new Error('You can only connect a Plaid account to a host account');
  }

  // Make sure this link token was generated by this user, for this host
  await assertPlaidLinkTokenWasInitiatedBy(remoteUser, host.id, linkToken);

  // Exchange Plaid public token
  let exchangeTokenResponse: ItemPublicTokenExchangeResponse;
  try {
    const PlaidClient = getPlaidClient();
    const exchangeTokenAxiosResponse = await PlaidClient.itemPublicTokenExchange({
      /* eslint-disable camelcase */
      public_token: publicToken,
      /* eslint-enable camelcase */
    });

    exchangeTokenResponse = exchangeTokenAxiosResponse.data;
  } catch (error) {
    const errorData = error.response?.data;
    if (!errorData) {
      throw new Error('A network occurred while connecting Plaid');
    } else if (errorData.error_code === 'INVALID_PUBLIC_TOKEN') {
      throw new Error('Provided Plaid public token is invalid');
    } else {
      reportErrorToSentry(error, { extra: { errorData }, user: remoteUser });
      throw new Error('An error occurred while connecting Plaid');
    }
  }

  // Create connected account
  const result = await sequelize.transaction(async transaction => {
    const connectedAccount = await ConnectedAccount.create(
      {
        CollectiveId: host.id,
        service: Service.PLAID,
        clientId: exchangeTokenResponse['item_id'],
        token: exchangeTokenResponse['access_token'],
        CreatedByUserId: remoteUser.id,
        data: omit(exchangeTokenResponse, ['item_id', 'access_token']),
      },
      { transaction },
    );

    const transactionsImport = await TransactionsImport.createWithActivity(
      remoteUser,
      host,
      {
        type: 'PLAID',
        source: truncate(sourceName, { length: 255 }) || 'Bank',
        name: truncate(name, { length: 255 }) || 'Bank Account',
        ConnectedAccountId: connectedAccount.id,
      },
      { transaction },
    );

    // Record the transactions import ID in the connected account for audit purposes
    await connectedAccount.update(
      {
        data: {
          ...connectedAccount.data,
          transactionsImportId: transactionsImport.id,
        },
      },
      { transaction },
    );

    return { connectedAccount, transactionsImport };
  });

  // Try to update the list of sub accounts. This is not critical, so we don't fail the whole import if it doesn't work
  try {
    await refreshPlaidSubAccounts(result.connectedAccount, result.transactionsImport);
  } catch (error) {
    reportErrorToSentry(error, { user: remoteUser, extra: { connectedAccountId: result.connectedAccount.id } });
  } finally {
    await clearPlaidLinkSession(linkToken);
  }

  return result;
};

export const disconnectPlaidAccount = async (connectedAccount: ConnectedAccount): Promise<void> => {
  if (connectedAccount.service !== Service.PLAID) {
    throw new Error('Only Plaid accounts can be disconnected');
  }

  const PlaidClient = getPlaidClient();
  try {
    await PlaidClient.itemRemove({
      /* eslint-disable camelcase */
      access_token: connectedAccount.token,
      /* eslint-enable camelcase */
    });
  } catch (error) {
    const errorData = error.response?.data;
    if (!errorData) {
      throw new Error('A network error occurred while disconnecting the Plaid account');
    } else if (errorData.error_code === 'INVALID_ACCESS_TOKEN') {
      throw new Error('Provided Plaid access token is invalid');
    } else {
      reportErrorToSentry(error, { extra: { errorData } });
      throw new Error('An error occurred while disconnecting the Plaid account');
    }
  }

  await TransactionsImport.update({ ConnectedAccountId: null }, { where: { ConnectedAccountId: connectedAccount.id } });
};

export const refreshPlaidSubAccounts = async (
  connectedAccount: ConnectedAccount,
  transactionsImport: TransactionsImport,
) => {
  if (transactionsImport.type !== 'PLAID') {
    throw new Error('Only Plaid transactions imports can be refreshed');
  } else if (transactionsImport.ConnectedAccountId !== connectedAccount.id) {
    throw new Error('The connected account does not match the transactions import');
  }

  const PlaidClient = getPlaidClient();
  const { data } = await PlaidClient.accountsGet({ access_token: connectedAccount.token }); // eslint-disable-line camelcase
  await transactionsImport.update({
    data: {
      plaid: {
        availableAccounts: data.accounts.map(account => ({
          accountId: account.account_id,
          mask: account.mask,
          name: account.name,
          officialName: account.official_name,
          subtype: account.subtype,
          type: account.type,
        })),
      },
    },
  });
};
