services:
  search:
    image: opensearchproject/opensearch:3
    profiles: [full, search]
    ports:
      - 9200:9200
      - 9600:9600
    deploy:
      resources:
        limits:
          cpus: '${OPENSEARCH_CPU_LIMIT:-0.50}'
          memory: '${OPENSEARCH_MEMORY_LIMIT:-12gb}'
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - cluster.routing.allocation.disk.watermark.low=98%
      - cluster.routing.allocation.disk.watermark.high=99%
      - cluster.routing.allocation.disk.watermark.flood_stage=99.5%
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m' # Set min and max JVM heap sizes to at least 50% of system RAM
      - 'DISABLE_INSTALL_DEMO_CONFIG=true' # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - 'DISABLE_SECURITY_PLUGIN=true' # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
  mailpit:
    image: axllent/mailpit
    profiles: [full, mail, debug, dev]
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./test/output/emails-data:/data
    ports:
      - 1080:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  minio:
    image: minio/minio:latest
    profiles: [full, dev, uploads]
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data
    command: server /data --console-address :9001

volumes:
  minio:
