version: '2'
services:
  api:
    build: .
    links:
      - postgres
    ports:
    - 3060:3060
    environment:
      NODE_ENV: production
      SEQUELIZE_ENV: production
      PG_URL: "postgres://opencollective:opencollective@postgres:5432/opencollective"
      PG_HOST: postgres
      PG_DATABASE: opencollective
      PG_USERNAME: opencollective
      PG_PASSWORD: opencollective
      API_URL: http://localhost:3060
      WEBAPP_URL: http://localhost:3060/app
      WEBSITE_URL: http://localhost:3000
      API_KEY: dvl-1510egmf4a23d80342403fb599qd
      PORT: 3060
      WEBSITE_URL: http://localhost:3000
      SESSION_SECRET: i&j@/V6Wx.`g>Aq?qQQF(>u)/Erm;3A=
  postgres:
    image: kartoza/postgis:9.6-2.4
    # volumes:
    # - /path/to/persistent/db:/var/lib/postgresql
    ports:
    - 15432:5432
    environment:
      POSTGRES_DBNAME: opencollective
      POSTGRES_USER: opencollective
      POSTGRES_PASS: opencollective
