/* eslint-disable camelcase */

export const klippaSuccessInvoice = {
  result: 'success',
  data: {
    parsed: {
      document_type: 'invoice',
      full_document_type: [
        { classification: 'financial', confidence: 1 },
        { classification: 'invoice', confidence: 0.97 },
        { classification: 'professional_services', confidence: 0.33 },
      ],
      amount: 6500,
      amount_change: 0,
      amount_shipping: 0,
      amount_tip: 0,
      vatamount: 0,
      amountexvat: 6500,
      currency: 'USD',
      date: '2023-08-01T00:00:00',
      purchasedate: '2023-08-01',
      purchasetime: '00:00:00',
      date_of_arrival: '',
      date_of_departure: '',
      service_date: '',
      vatitems: [],
      vat_context: '',
      lines: [
        {
          description: '',
          lineitems: [
            {
              title: 'Mocked test item 1',
              description: '',
              amount: 0,
              amount_each: 0,
              amount_ex_vat: 0,
              quantity: 1,
              vat_amount: 0,
              vat_percentage: 0,
              vat_code: '',
              unit_of_measurement: '',
              sku: '',
              ean: '',
              order_number: '',
              line_number: '',
              discount_percentage: 0,
              discount_amount: 0,
              discount_code: '',
              matched_purchase_order: null,
            },
            {
              title: 'Mocked test item 2',
              description: '',
              amount: 3200,
              amount_each: 3200,
              amount_ex_vat: 3200,
              quantity: 1,
              vat_amount: 0,
              vat_percentage: 0,
              vat_code: '',
              unit_of_measurement: '',
              sku: '',
              ean: '',
              order_number: '',
              line_number: '',
              discount_percentage: 0,
              discount_amount: 0,
              discount_code: '',
              matched_purchase_order: null,
            },
            {
              title: 'Mocked test item 3',
              description: '',
              amount: 1400,
              amount_each: 1400,
              amount_ex_vat: 1400,
              quantity: 1,
              vat_amount: 0,
              vat_percentage: 0,
              vat_code: '',
              unit_of_measurement: '',
              sku: '',
              ean: '',
              order_number: '',
              line_number: '',
              discount_percentage: 0,
              discount_amount: 0,
              discount_code: '',
              matched_purchase_order: null,
            },
            {
              title: 'Mocked test item 4',
              description: '',
              amount: 1900,
              amount_each: 1900,
              amount_ex_vat: 1900,
              quantity: 1,
              vat_amount: 0,
              vat_percentage: 0,
              vat_code: '',
              unit_of_measurement: '',
              sku: '',
              ean: '',
              order_number: '',
              line_number: '',
              discount_percentage: 0,
              discount_amount: 0,
              discount_code: '',
              matched_purchase_order: null,
            },
          ],
        },
      ],
      paymentmethod: 'creditcard',
      payment_auth_code: '',
      payment_card_number: '4242',
      payment_card_account_number: '4242',
      payment_card_bank: '',
      payment_card_issuer: '',
      payment_due_date: '',
      terminal_number: '',
      document_subject: '',
      package_number: '',
      invoice_number: '3533E619-0024',
      invoice_type: 'invoice',
      receipt_number: '2943-3508',
      shop_number: '',
      transaction_number: '',
      transaction_reference: '',
      order_number: '',
      table_number: '',
      table_group: '',
      server: '',
      merchant_name: 'TestMerchant',
      merchant_id: '',
      merchant_coc_number: '',
      merchant_vat_number: '',
      merchant_fiscal_number: '',
      merchant_bank_account_number: '',
      merchant_bank_account_number_bic: '',
      merchant_chain_liability_bank_account_number: '',
      merchant_chain_liability_amount: 0,
      merchant_bank_domestic_account_number: '',
      merchant_bank_domestic_bank_code: '',
      merchant_website: 'http://dashboard.agreatvendor.com',
      merchant_email: 'support@agreatvendor.com',
      merchant_address: '',
      merchant_street_name: '',
      merchant_house_number: '',
      merchant_zipcode: '',
      merchant_city: '',
      merchant_municipality: '',
      merchant_province: '',
      merchant_country: '',
      merchant_country_code: 'FR',
      merchant_phone: '',
      merchant_main_activity_code: '',
      customer_id: '',
      customer_name: 'MySuperProject',
      customer_number: '',
      customer_reference: '',
      customer_address: '',
      customer_street_name: '',
      customer_house_number: '',
      customer_zipcode: '',
      customer_city: '',
      customer_municipality: '',
      customer_province: '',
      customer_country: '',
      customer_phone: '',
      customer_vat_number: '',
      customer_fiscal_number: '',
      customer_coc_number: '',
      customer_bank_account_number: '',
      customer_bank_account_number_bic: '',
      customer_website: '',
      customer_email: 'developers@MySuperProject.io',
      payment_slip_code: '',
      payment_slip_reference_number: '',
      payment_slip_customer_number: '',
      document_language: 'EN',
      personal_income_tax_amount: 0,
      personal_income_tax_rate: 0,
      project_code: '',
      matched_keywords: null,
      matched_lineitems: null,
      matched_purchase_order_id: '',
      matched_purchase_orders: null,
      matched_project_code_id: '',
      matched_entity_id: null,
      barcodes: null,
      hash: 'abcdefghijklmnoparstuvwxyz',
      hash_duplicate: true,
      raw_text:
        'Receipt                                                                                              render\nInvoice number   3533E619-0024\nReceipt number   2943-3508\nDate paid        August 1, 2023\nPayment method   Visa - 4242\nBilling period   Jul 1 - Jul 31, 2023\nTeam name        MySuperProject\nRender                                                      Bill to\n525 Brannan St                                              MySuperProject\nSte 300                                                     My Street Address\nSan Francisco, California 94107                             My City\nUnited States                                               PAC\nsupport@agreatvendor.com                                          86666\n                                                            France\n                                                            developers@MySuperProject.io\n$65.00 paid on August 1, 2023\nRender Jul 1, 2023 - Jul 31, 2023\nDescription                                                 Qty                 Unit price                        Amount\nStatic Sites - 743h 59m 59s - 1 instance                    1                   $0.00                             $0.00\nServers - 2,231h 59m 57s - 3 instances                      1                   $32.00                           $32.00\nPostgresDB - 1,487h 59m 58s - 2 instances                   1                   $14.00                           $14.00\nTeam Plan - 1 user                                          1                   $19.00                           $19.00\n                                                            Subtotal                                             $65.00\n                                                            Total                                                $65.00\n                                                            Amount paid                                          $65.00\nSee https://dashboard.agreatvendor.com/billing for usage details.\n2943-3508 $65.00 paid on August 1, 2023                                                                        Page 1 of 1',
    },
    fields: null,
    quality: {
      blurriness: 0,
      over_exposed: 0.96,
      under_exposed: 0,
      characters: 648,
      unsupported_chars: 0,
      non_text_chars: 0.06,
      unknown_document_type: 0,
    },
    vision_files: null,
    raw_text:
      'Receipt                                                                                              render\nInvoice number   3533E619-0024\nReceipt number   2943-3508\nDate paid        August 1, 2023\nPayment method   Visa - 4242\nBilling period   Jul 1 - Jul 31, 2023\nTeam name        MySuperProject\nRender                                                      Bill to\n525 Brannan St                                              MySuperProject\nSte 300                                                     My Street Address\nSan Francisco, California 94107                             My City\nUnited States                                               PAC\nsupport@agreatvendor.com                                          86666\n                                                            France\n                                                            developers@MySuperProject.io\n$65.00 paid on August 1, 2023\nRender Jul 1, 2023 - Jul 31, 2023\nDescription                                                 Qty                 Unit price                        Amount\nStatic Sites - 743h 59m 59s - 1 instance                    1                   $0.00                             $0.00\nServers - 2,231h 59m 57s - 3 instances                      1                   $32.00                           $32.00\nPostgresDB - 1,487h 59m 58s - 2 instances                   1                   $14.00                           $14.00\nTeam Plan - 1 user                                          1                   $19.00                           $19.00\n                                                            Subtotal                                             $65.00\n                                                            Total                                                $65.00\n                                                            Amount paid                                          $65.00\nSee https://dashboard.agreatvendor.com/billing for usage details.\n2943-3508 $65.00 paid on August 1, 2023                                                                        Page 1 of 1',
    hash: 'abcdefghijklmnoparstuvwxyz',
    hash_duplicate: true,
  },
  request_id: 'x424242424242',
};

export const klippaSuccessReceiptWithVAT = {
  result: 'success',
  request_id: 'xxxxxxxxxxxxxxxxyyyyzz',
  data: {
    hash: '5092af1073e8c23a3b629c8a98f82ff7b9172d3a',
    fields: null,
    parsed: {
      date: '2022-07-20T19:02:00',
      hash: '5092af1073e8c23a3b629c8a98f82ff7b9172d3a',
      lines: [
        {
          lineitems: [
            {
              ean: '',
              sku: '',
              title: 'OASI',
              amount: 11999,
              quantity: 1,
              vat_code: '',
              vat_amount: 0,
              amount_each: 11999,
              description: '',
              line_number: '',
              order_number: '',
              amount_ex_vat: 11999,
              discount_code: '',
              vat_percentage: 0,
              discount_amount: 0,
              discount_percentage: 0,
              unit_of_measurement: '',
              matched_purchase_order: null,
            },
            {
              ean: '',
              sku: '2-2798\n1017419',
              title: 'WINSTED BAMBOO DARK OLIVE',
              amount: 5490,
              quantity: 1,
              vat_code: '',
              vat_amount: 0,
              amount_each: 5490,
              description: '',
              line_number: '',
              order_number: '',
              amount_ex_vat: 5490,
              discount_code: '',
              vat_percentage: 0,
              discount_amount: 0,
              discount_percentage: 0,
              unit_of_measurement: '',
              matched_purchase_order: null,
            },
          ],
          description: '',
        },
      ],
      amount: 17489,
      server: '',
      barcodes: null,
      currency: 'EUR',
      raw_text:
        '         APPROACH DEVIENT CHULLANKA\n         VOS SPORTS GRANDEUR NATURE\n               CHULLANKA.COM\n *******    *****                    ******\n                   ****\n              ORIGINAL\n0-34970 OASI TENAYA\nUnicolor • 41\nOASI                             119,99 €\n2-2798 WINSTED BAMBOO DARK OLIVE\nUNICOLOR - 8\nAPP_TEV 1017419                   54,90 €\nNET À PAYER                      174,89 €\n(2 Articles)\nCARTES BLEUES                    174,89 €\n  Taux |       HT I      TVA I       TTC\n 20,00%    145,74 |    29,15 |    174,89\n**************\n                   ****\n          APPROACH >>> CHULLANKA\n             RUE ARNAUD BORILI\n          ZONE COMMERCIAL PIOLINE\n           13290 AIX EN PROVENCE\n           TEL: 04.42.12.74.25\n           MERCI DE VOTRE VISITE\n          SIRET 79759906500019\nTicket N° : TI-16-A8Q-73-19-37\nle 20/07/2022 à 19:02\nf.lamy\n         TK-398023106',
      vatitems: [
        {
          code: '',
          amount: 2915,
          percentage: 2000,
          amount_excl_vat: 14574,
          amount_incl_vat: 17489,
          amount_incl_excl_vat_estimated: false,
        },
      ],
      vatamount: 2915,
      amount_tip: 0,
      amountexvat: 14574,
      customer_id: '',
      merchant_id: '',
      shop_number: '',
      table_group: '',
      vat_context: '',
      invoice_type: '',
      order_number: '',
      project_code: '',
      purchasedate: '2022-07-20',
      purchasetime: '19:02:00',
      service_date: '',
      table_number: '',
      amount_change: 0,
      customer_city: '',
      customer_name: '',
      document_type: 'receipt',
      merchant_city: '',
      merchant_name: 'Chullanka',
      paymentmethod: '',
      customer_email: '',
      customer_phone: '',
      hash_duplicate: false,
      invoice_number: 'TI-16-A8Q-73-19-37',
      merchant_email: '',
      merchant_phone: '0442127425',
      package_number: '',
      receipt_number: 'TI-16-A8Q-73-19-37',
      amount_shipping: 0,
      customer_number: '',
      date_of_arrival: '',
      terminal_number: '',
      customer_address: '',
      customer_country: '',
      customer_website: '',
      customer_zipcode: '',
      document_subject: '',
      matched_keywords: null,
      merchant_address: '',
      merchant_country: '',
      merchant_website: 'http://chullanka.com',
      merchant_zipcode: '',
      payment_due_date: '',
      customer_province: '',
      date_of_departure: '',
      document_language: 'FR',
      matched_entity_id: null,
      matched_lineitems: null,
      merchant_province: '',
      payment_auth_code: '',
      payment_card_bank: '',
      payment_slip_code: '',
      customer_reference: '',
      full_document_type: [
        {
          confidence: 1,
          classification: 'financial',
        },
        {
          confidence: 0.97,
          classification: 'receipt',
        },
        {
          confidence: 0.84,
          classification: 'retail',
        },
      ],
      transaction_number: '',
      customer_coc_number: '',
      customer_vat_number: '',
      merchant_coc_number: '79759906500019',
      merchant_vat_number: '',
      payment_card_issuer: '',
      payment_card_number: '',
      customer_street_name: '',
      merchant_street_name: '',
      customer_house_number: '',
      customer_municipality: '',
      merchant_country_code: 'FR',
      merchant_house_number: '',
      merchant_municipality: '',
      transaction_reference: '',
      customer_fiscal_number: '',
      merchant_fiscal_number: '',
      matched_project_code_id: '',
      matched_purchase_orders: null,
      personal_income_tax_rate: 0,
      matched_purchase_order_id: '',
      personal_income_tax_amount: 0,
      merchant_main_activity_code: '',
      payment_card_account_number: '',
      customer_bank_account_number: '',
      merchant_bank_account_number: '',
      payment_slip_customer_number: '',
      payment_slip_reference_number: '',
      merchant_chain_liability_amount: 0,
      customer_bank_account_number_bic: '',
      merchant_bank_account_number_bic: '',
      merchant_bank_domestic_bank_code: '',
      merchant_bank_domestic_account_number: '',
      merchant_chain_liability_bank_account_number: '',
    },
    quality: {
      blurriness: 0.53,
      characters: 399,
      over_exposed: 0,
      under_exposed: 0,
      non_text_chars: 0.15,
      unsupported_chars: 0.01,
      unknown_document_type: 0,
    },
    raw_text:
      '         APPROACH DEVIENT CHULLANKA\n         VOS SPORTS GRANDEUR NATURE\n               CHULLANKA.COM\n *******    *****                    ******\n                   ****\n              ORIGINAL\n0-34970 OASI TENAYA\nUnicolor • 41\nOASI                             119,99 €\n2-2798 WINSTED BAMBOO DARK OLIVE\nUNICOLOR - 8\nAPP_TEV 1017419                   54,90 €\nNET À PAYER                      174,89 €\n(2 Articles)\nCARTES BLEUES                    174,89 €\n  Taux |       HT I      TVA I       TTC\n 20,00%    145,74 |    29,15 |    174,89\n**************\n                   ****\n          APPROACH >>> CHULLANKA\n             RUE ARNAUD BORILI\n          ZONE COMMERCIAL PIOLINE\n           13290 AIX EN PROVENCE\n           TEL: 04.42.12.74.25\n           MERCI DE VOTRE VISITE\n          SIRET 79759906500019\nTicket N° : TI-16-A8Q-73-19-37\nle 20/07/2022 à 19:02\nf.lamy\n         TK-398023106',
    vision_files: null,
    hash_duplicate: false,
  },
};

/**
 * Generated from a picture of potatoes, this document can't be used to prefill the expense form
 * (all fields are empty).
 */
export const klippaSuccessRandomImage = {
  result: 'success',
  request_id: 'fdslfmsdlkgmfldkgdskgjfdlgnfjf',
  data: {
    parsed: {
      document_type: '',
      full_document_type: null,
      amount: 0,
      amount_change: 0,
      amount_shipping: 0,
      amount_tip: 0,
      vatamount: 0,
      amountexvat: 0,
      currency: '',
      date: '',
      purchasedate: '',
      purchasetime: '',
      date_of_arrival: '',
      date_of_departure: '',
      service_date: '',
      vatitems: [],
      vat_context: '',
      lines: [],
      paymentmethod: '',
      payment_auth_code: '',
      payment_card_number: '',
      payment_card_account_number: '',
      payment_card_bank: '',
      payment_card_issuer: '',
      payment_due_date: '',
      terminal_number: '',
      document_subject: '',
      package_number: '',
      invoice_number: '',
      invoice_type: '',
      receipt_number: '',
      shop_number: '',
      transaction_number: '',
      transaction_reference: '',
      order_number: '',
      table_number: '',
      table_group: '',
      server: '',
      merchant_name: '',
      merchant_id: '',
      merchant_coc_number: '',
      merchant_vat_number: '',
      merchant_fiscal_number: '',
      merchant_bank_account_number: '',
      merchant_bank_account_number_bic: '',
      merchant_chain_liability_bank_account_number: '',
      merchant_chain_liability_amount: 0,
      merchant_bank_domestic_account_number: '',
      merchant_bank_domestic_bank_code: '',
      merchant_website: '',
      merchant_email: '',
      merchant_address: '',
      merchant_street_name: '',
      merchant_house_number: '',
      merchant_zipcode: '',
      merchant_city: '',
      merchant_municipality: '',
      merchant_province: '',
      merchant_country: '',
      merchant_country_code: '',
      merchant_phone: '',
      merchant_main_activity_code: '',
      customer_id: '',
      customer_name: '',
      customer_number: '',
      customer_reference: '',
      customer_address: '',
      customer_street_name: '',
      customer_house_number: '',
      customer_zipcode: '',
      customer_city: '',
      customer_municipality: '',
      customer_province: '',
      customer_country: '',
      customer_phone: '',
      customer_vat_number: '',
      customer_fiscal_number: '',
      customer_coc_number: '',
      customer_bank_account_number: '',
      customer_bank_account_number_bic: '',
      customer_website: '',
      customer_email: '',
      payment_slip_code: '',
      payment_slip_reference_number: '',
      payment_slip_customer_number: '',
      document_language: '',
      personal_income_tax_amount: 0,
      personal_income_tax_rate: 0,
      project_code: '',
      matched_keywords: null,
      matched_lineitems: null,
      matched_purchase_order_id: '',
      matched_purchase_orders: null,
      matched_project_code_id: '',
      matched_entity_id: null,
      barcodes: null,
      hash: '',
      hash_duplicate: false,
      raw_text: '',
    },
    fields: null,
    quality: null,
    vision_files: null,
    raw_text: '',
    hash: '',
    hash_duplicate: false,
  },
};
