services:
  mailpit:
    image: docker.io/axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 1080:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    deploy:
      resources:
        limits:
          cpus: '${MAILPIT_CPU_LIMIT:-0.10}'
          memory: '${MAILPIT_MEMORY_LIMIT:-1gb}'
volumes:
  mailpit-data: