services:
  rustfs:
    image: docker.io/rustfs/rustfs:1.0.0-rc.6
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: user
      RUSTFS_SECRET_KEY: password
    deploy:
      resources:
        limits:
          cpus: '${RUSTFS_CPU_LIMIT:-0.25}'
          memory: '${RUSTFS_MEMORY_LIMIT:-2gb}'
    volumes:
      - rustfs:/data

volumes:
  rustfs:
