services:
  minio:
    image: docker.io/minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    deploy:
      resources:
        limits:
          cpus: '${MINIO_CPU_LIMIT:-0.25}'
          memory: '${MINIO_MEMORY_LIMIT:-2gb}'
    volumes:
      - minio:/data
    command: server /data --console-address :9001

volumes:
  minio: