import { GraphQLEnumType } from 'graphql';

import expenseType from '../../../constants/expense_type.js';

export const GraphQLExpenseType = new GraphQLEnumType({
  name: 'ExpenseType',
  description: 'All supported expense types',
  values: {
    [expenseType.INVOICE]: {
      description: 'Invoice: Charge for your time or get paid in advance.',
    },
    [expenseType.RECEIPT]: {
      description: 'Receipt: Get paid back for a purchase already made.',
    },
    [expenseType.FUNDING_REQUEST]: {
      description: 'Funding Request: Request funding for a project or initiative.', // to be replaced by GRANT
    },
    [expenseType.GRANT]: {
      description: 'Grant: Request funding for a project or initiative.',
    },
    [expenseType.UNCLASSIFIED]: {
      description: 'Unclassified expense',
    },
    [expenseType.CHARGE]: {
      description: 'Credit Card Charge: Payment done using an issued (virtual) credit card issued by your Fiscal Host.',
    },
    [expenseType.SETTLEMENT]: {
      description: 'Settlement: expense generated by Open Collective to collect money owed by Fiscal Hosts.',
    },
  },
});
