import DataLoader from 'dataloader';
import { DataTypes, ForeignKey, InferAttributes, Model } from 'sequelize';
import Temporal from 'sequelize-temporal';

import { sortResultsSimple } from '../graphql/loaders/helpers';
import sequelize from '../lib/sequelize';

import Collective from './Collective';

export enum KYCProviderName {
  MANUAL = 'manual',
}

export enum KYCVerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

type KycProviderData = {
  [KYCProviderName.MANUAL]: {
    notes: string;
  };
};

type KYCVerifiedData = {
  legalName: string;
  legalAddress: string;
};

type KYCData<Provider extends KYCProviderName = KYCProviderName> = Provider extends keyof KycProviderData
  ? KycProviderData[Provider]
  : unknown;

export class KYCVerification<Provider extends KYCProviderName = KYCProviderName> extends Model<
  InferAttributes<KYCVerification>,
  KYCVerification
> {
  declare id: number;
  declare CollectiveId: ForeignKey<Collective['id']>;
  declare RequestedByCollectiveId: ForeignKey<Collective['id']>;

  declare provider: Provider;
  declare status: KYCVerificationStatus;
  /** verified data generated by provider in standard schema */
  declare data: KYCVerifiedData;
  /** provider specific data */
  declare providerData: KYCData<Provider>;

  declare verifiedAt?: Date;
  declare revokedAt?: Date;

  declare createdAt: Date;
  declare updatedAt: Date;
  declare deletedAt?: Date;

  static get loaders() {
    const byRequestedByCollectiveId = {
      verifiedStatusByProvider: {},
    };
    function verifiedStatusByProvider(
      RequestedByCollectiveId: number,
      provider: KYCProviderName,
    ): DataLoader<number, KYCVerification> {
      if (byRequestedByCollectiveId.verifiedStatusByProvider[provider]?.[RequestedByCollectiveId]) {
        return byRequestedByCollectiveId.verifiedStatusByProvider[provider][RequestedByCollectiveId];
      }

      if (!byRequestedByCollectiveId.verifiedStatusByProvider[provider]) {
        byRequestedByCollectiveId.verifiedStatusByProvider[provider] = {};
      }

      byRequestedByCollectiveId.verifiedStatusByProvider[provider][RequestedByCollectiveId] = new DataLoader<
        number,
        KYCVerification
      >(async keys => {
        const res: KYCVerification[] = await sequelize.query(
          `
          WITH verified_status AS (
            SELECT 
              "kyc".*,
              RANK() OVER(PARTITION BY "kyc"."CollectiveId" ORDER BY "kyc"."verifiedAt" DESC) "_rank"
            FROM "KYCVerifications" "kyc"
            WHERE
              "kyc"."status" = :status AND
              "kyc"."provider" = :provider AND
              "kyc"."RequestedByCollectiveId" = :RequestedByCollectiveId AND
              "kyc"."CollectiveId" IN (:CollectiveId)              
          ) SELECT * from verified_status WHERE "_rank" = 1;
          
        `,
          {
            type: sequelize.QueryTypes.SELECT,
            model: KYCVerification,
            mapToModel: true,
            replacements: {
              status: KYCVerificationStatus.VERIFIED,
              provider,
              RequestedByCollectiveId,
              CollectiveId: keys,
            },
          },
        );

        return sortResultsSimple(keys, res, i => i.CollectiveId);
      });

      return byRequestedByCollectiveId.verifiedStatusByProvider[provider][RequestedByCollectiveId];
    }
    return {
      verifiedStatusByProvider,
    };
  }
}

KYCVerification.init(
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
    },
    CollectiveId: {
      type: DataTypes.INTEGER,
      references: { key: 'id', model: 'Collectives' },
      allowNull: false,
    },
    RequestedByCollectiveId: {
      type: DataTypes.INTEGER,
      references: { key: 'id', model: 'Collectives' },
      allowNull: false,
    },
    data: {
      type: DataTypes.JSONB,
      allowNull: false,
      defaultValue: sequelize.literal(`'{}'`),
    },
    providerData: {
      type: DataTypes.JSONB,
      allowNull: false,
      defaultValue: sequelize.literal(`'{}'`),
    },
    provider: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    status: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: KYCVerificationStatus.PENDING,
    },
    verifiedAt: {
      type: DataTypes.DATE,
    },
    revokedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      allowNull: false,
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      allowNull: false,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
  },
  {
    sequelize,
    tableName: 'KYCVerifications',
    paranoid: true,
  },
);

Temporal(KYCVerification, sequelize);
