import { get } from 'lodash';

import { types } from '../constants/collectives';
import FEATURE from '../constants/feature';
import models from '../models';

import { isPastEvent } from './collectivelib';

const HOST_TYPES = [types.USER, types.ORGANIZATION];

// Please refer to and update https://docs.google.com/spreadsheets/d/15ppKaZJCXBjvY7-AjjCj3w5D-4ebLQdEowynJksgDXE/edit#gid=0
const FeatureAllowedForTypes = {
  [FEATURE.RECEIVE_FINANCIAL_CONTRIBUTIONS]: [
    types.ORGANIZATION,
    types.COLLECTIVE,
    types.EVENT,
    types.FUND,
    types.PROJECT,
  ],
  [FEATURE.RECURRING_CONTRIBUTIONS]: [types.USER, types.ORGANIZATION, types.COLLECTIVE, types.FUND],
  [FEATURE.RECEIVE_HOST_APPLICATIONS]: HOST_TYPES,
  [FEATURE.HOST_DASHBOARD]: HOST_TYPES,
  [FEATURE.EVENTS]: [types.ORGANIZATION, types.COLLECTIVE],
  [FEATURE.PROJECTS]: [types.FUND],
  [FEATURE.USE_EXPENSES]: [types.ORGANIZATION, types.COLLECTIVE, types.EVENT, types.FUND, types.PROJECT],
  [FEATURE.RECEIVE_EXPENSES]: [types.ORGANIZATION, types.COLLECTIVE, types.EVENT, types.FUND, types.PROJECT],
  [FEATURE.COLLECTIVE_GOALS]: [types.COLLECTIVE, types.ORGANIZATION],
  [FEATURE.TOP_FINANCIAL_CONTRIBUTORS]: [types.COLLECTIVE, types.ORGANIZATION, types.FUND],
  [FEATURE.CONVERSATIONS]: [types.COLLECTIVE, types.ORGANIZATION],

};

const FEATURES_ONLY_FOR_HOST_ORGS = new Set([
  FEATURE.RECEIVE_FINANCIAL_CONTRIBUTIONS,
  FEATURE.USE_EXPENSES,
  FEATURE.RECEIVE_EXPENSES,
  FEATURE.RECEIVE_HOST_APPLICATIONS,
  FEATURE.TOP_FINANCIAL_CONTRIBUTORS,
  FEATURE.COLLECTIVE_GOALS,
  FEATURE.TRANSFERWISE,
  FEATURE.PAYPAL_PAYOUTS,
  FEATURE.PAYPAL_DONATIONS,
  FEATURE.CONTACT_FORM,
  FEATURE.HOST_DASHBOARD,
  FEATURE.EVENTS,
  FEATURE.UPDATES,
  FEATURE.CONVERSATIONS,
]);

const FEATURES_ONLY_FOR_HOST_USERS = new Set([FEATURE.RECEIVE_HOST_APPLICATIONS, FEATURE.HOST_DASHBOARD]);

const FEATURES_ONLY_FOR_ACTIVE_ACCOUNTS = new Set([FEATURE.CONTACT_FORM]);

const FEATURES_ONLY_FOR_ACTIVE_HOSTS = new Set([
  FEATURE.RECEIVE_EXPENSES,
  FEATURE.RECEIVE_FINANCIAL_CONTRIBUTIONS,
  FEATURE.EVENTS,
]);

const FEATURES_DISABLED_FOR_PAST_EVENTS = new Set([FEATURE.RECEIVE_FINANCIAL_CONTRIBUTIONS]);

/**

  if (!allowedForType) {
    return false;
  }


    return false;
  }

  return true;
};


  if (!collective) {
    return false;
  }
};

export { FEATURE };
