enum FEATURE {
  // Collective page features
  RECEIVE_FINANCIAL_CONTRIBUTIONS = 'RECEIVE_FINANCIAL_CONTRIBUTIONS',
  RECURRING_CONTRIBUTIONS = 'RECURRING_CONTRIBUTIONS',
  EVENTS = 'EVENTS',
  PROJECTS = 'PROJECTS',
  USE_EXPENSES = 'USE_EXPENSES',
  RECEIVE_EXPENSES = 'RECEIVE_EXPENSES',
  RECEIVE_HOST_APPLICATIONS = 'RECEIVE_HOST_APPLICATIONS',
  COLLECTIVE_GOALS = 'COLLECTIVE_GOALS',
  TOP_FINANCIAL_CONTRIBUTORS = 'TOP_FINANCIAL_CONTRIBUTORS',
  CONVERSATIONS = 'CONVERSATIONS',
  UPDATES = 'UPDATES',
  TEAM = 'TEAM',
  // Other
  ORDER = 'ORDER',
  CONTACT_COLLECTIVE = 'CONTACT_COLLECTIVE',
  CONTACT_FORM = 'CONTACT_FORM',
  CREATE_COLLECTIVE = 'CREATE_COLLECTIVE',
  TRANSACTIONS = 'TRANSACTIONS',
  CROSS_CURRENCY_MANUAL_TRANSACTIONS = 'CROSS_CURRENCY_MANUAL_TRANSACTIONS',
  TRANSFERWISE = 'TRANSFERWISE',
  PAYPAL_PAYOUTS = 'PAYPAL_PAYOUTS',
  PAYPAL_DONATIONS = 'PAYPAL_DONATIONS',
  HOST_DASHBOARD = 'HOST_DASHBOARD',
  CONNECTED_ACCOUNTS = 'CONNECTED_ACCOUNTS',
}

export const FeaturesList = Object.values(FEATURE);

export default FEATURE;
