export enum MODERATION_CATEGORY {
  ADULT = 'ADULT',
  AFFILIATE_REVIEW = 'AFFILIATE_REVIEW',
  CASINO_GAMBLING = 'CASINO_GAMBLING',
  SEO_AUDIENCE = 'SEO_AUDIENCE',
  VPN_PROXY = 'VPN_PROXY',
  WRITER = 'WRITER',
}

export const MODERATION_CATEGORIES = Object.values(MODERATION_CATEGORY);
