export enum EXPENSE_PERMISSION_ERROR_CODES {
  UNSUPPORTED_STATUS = 'UNSUPPORTED_STATUS',
  UNSUPPORTED_USER_FEATURE = 'UNSUPPORTED_USER_FEATURE',
  MINIMAL_CONDITION_NOT_MET = 'MINIMAL_CONDITION_NOT_MET',
}
