export enum EXPENSE_PERMISSION_ERROR_CODES {
  UNSUPPORTED_STATUS = 'UNSUPPORTED_STATUS',
  UNSUPPORTED_TYPE = 'UNSUPPORTED_TYPE',
  UNSUPPORTED_USER_FEATURE = 'UNSUPPORTED_USER_FEATURE',
  MINIMAL_CONDITION_NOT_MET = 'MINIMAL_CONDITION_NOT_MET',
  AUTHOR_CANNOT_APPROVE = 'AUTHOR_CANNOT_APPROVE',
  INVALID_SCOPE = 'INVALID_SCOPE',
}
