enum Tiers {
  SINGLE_TICKET = 'SINGLE_TICKET',
  MULTIPLE_TICKET = 'MULTIPLE_TICKET',
  TIER = 'TIER',
  MEMBERSHIP = 'MEMBERSHIP',
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
  DONATION = 'DONATION',
}

export default Tiers;
